import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    console.log(savedLanguage || 'en')
    return savedLanguage || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key) => {
    const translations = {
      en: {
        // Navigation
        home: 'Home',
        dashboard: 'Dashboard',
        services: 'Services',
        wallet: 'Wallet',
        reports: 'Reports',
        login: 'Login',
        signup: 'Signup',
        logout: 'Logout',
        
        // Common
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        view: 'View',
        
        // User Dashboard
        balance: 'Balance',
        subscriptions: 'Active Subscriptions',
        noSubscriptions: 'No active subscriptions',
        subscribeNow: 'Subscribe Now',
        premiumNotification: 'To ensure better service subscribe to the premium plan',
        welcomeBack: 'Welcome Back!',
        dashboardSubtitle: 'Your AI-powered enterprise dashboard is running at peak performance',
        accountBalance: 'Account Balance',
        activeServices: 'Active Services',
        enterpriseEliteUpgrade: 'Enterprise Elite Upgrade Available',
        unlockQuantumProcessing: 'Unlock unlimited quantum processing and dedicated AI infrastructure',
        upgradeNow: 'Upgrade Now',
        accountStatus: 'Account Status',
        premium: 'Premium',
        performance: 'Performance',
        uptime: 'Uptime this month',
        optimal: 'Optimal',
        activeSubscriptions: 'Active Subscriptions',
        browseServices: 'Browse Services',
        noActiveSubscriptions: 'No Active Subscriptions',
        subscribeToPremium: 'Subscribe to our premium services to unlock advanced features',
        exploreServices: 'Explore Services',
        nextBilling: 'Next Billing',
        yourAchievements: 'Your Achievements',
        wallet: 'Wallet',
        manageYourFunds: 'Manage your funds',
        viewWallet: 'View Wallet',
        browsePremiumServices: 'Browse premium services',
        viewServices: 'View Services',
        advancedInsights: 'Advanced insights',
        comingSoon: 'Coming Soon',
        accountPreferences: 'Account preferences',
        settings: 'Settings',
        
        // Services
        price: 'Price',
        subscribe: 'Subscribe',
        subscribed: 'Subscribed',
        insufficientBalance: 'Insufficient balance',
        premiumServices: 'PREMIUM SERVICES',
        currentBalance: 'Current Balance',
        choosePerfectPlan: 'Choose the perfect plan for your needs and unlock powerful features',
        mostPopular: 'Most Popular',
        confirmSubscription: 'Confirm Subscription',
        currentBalanceLabel: 'Current Balance:',
        subscriptionCost: 'Subscription Cost:',
        balanceAfterSubscription: 'Balance After Subscription:',
        areYouSureSubscribe: 'Are you sure you want to subscribe to this service?',
        
        // Wallet
        walletRecharge: 'Wallet Recharge',
        phoneNumber: 'Phone Number',
        amount: 'Amount',
        uploadScreenshot: 'Upload Payment Screenshot',
        submit: 'Submit',
        rechargeForm: 'Recharge Form',
        paymentMethod: 'Payment Method',
        paymentDetails: 'Payment Details',
        sendPaymentTo: 'Send payment to:',
        includeUserIdInReference: 'Please include your user ID in the payment reference',
        howToRecharge: 'How to Recharge',
        selectPaymentMethod: 'Select your preferred payment method',
        enterAmount: 'Enter the amount you want to add',
        sendPayment: 'Send payment to the provided number/account',
        uploadPaymentProof: 'Upload payment screenshot as proof',
        submitForVerification: 'Submit for verification',
        notePaymentVerification: 'Note: Payment verification typically takes 1-24 hours. You\'ll receive a notification once your wallet is updated.',
        paymentScreenshotPreview: 'Payment Screenshot Preview',
        
        // Marketing Dashboard
        totalReferred: 'Total Referred Users',
        availableEarnings: 'Available Earnings',
        referralLink: 'Referral Link',
        paidReferrals: 'Paid Referrals',
        
        // Admin Dashboard
        totalUsers: 'Total Users',
        payingUsers: 'Paying Users',
        marketingUsers: 'Marketing Users',
        totalPaid: 'Total Paid Amount',
        marketingBudget: 'Marketing Budget',
        
        // Auth
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        rememberMe: 'Remember Me',
        forgotPassword: 'Forgot Password?',
        alreadyHaveAccount: 'Already have an account?',
        dontHaveAccount: "Don't have an account?",
        premiumAccess: 'PREMIUM ACCESS',
        createAccount: 'Create your account and get started today!',
        fullName: 'Full Name',
        enterFullName: 'Enter your full name',
        enterEmail: 'Enter your email',
        createPassword: 'Create a password',
        enterPassword: 'Enter your password',
        confirmPasswordLabel: 'Confirm your password',
        referralCodeOptional: 'Referral Code (Optional)',
        enterReferralCode: 'Enter referral code',
        
        // Landing
        welcome: 'Welcome to AI Platform',
        subtitle: 'Experience the future of AI-powered services',
        getStarted: 'Get Started',
        features: 'Features',
        about: 'About',
        contact: 'Contact',
        enterpriseGrade: 'ENTERPRISE GRADE',
        nextGenerationAI: 'Next-Generation AI Platform',
        transformBusiness: 'Transform your business with cutting-edge artificial intelligence and quantum computing technologies',
        startFreeTrial: 'Start Free Trial',
        viewDemo: 'View Demo',
        revolutionaryFeatures: 'Revolutionary Features',
        experienceFutureAI: 'Experience the future of AI with our cutting-edge technology stack',
        limitedTimeOffer: 'LIMITED TIME OFFER',
        readyToDominate: 'Ready to Dominate Your Industry?',
        joinEliteBusinesses: 'Join the elite businesses that are already leveraging our AI platform to achieve unprecedented growth and efficiency.',
        startYourJourney: 'Start Your Journey',
        scheduleDemo: 'Schedule Demo',
        rating: '4.9/5 Rating',
        secure: '100% Secure',
        enterpriseReady: 'Enterprise Ready',
        apiCalls: 'API Calls',
        responseTime: 'Response Time',
        support: 'Support',
        
        // Additional Service Names
        basicAnalytics: 'Basic Analytics',
        essentialAnalyticsBusiness: 'Essential analytics for your business with real-time insights',
        professionalAI: 'Professional AI',
        advancedAIPowered: 'Advanced AI-powered analytics with machine learning capabilities',
        enterpriseSuite: 'Enterprise Suite',
        completeEnterpriseSolution: 'Complete enterprise solution with unlimited features and support',
        securityPro: 'Security Pro',
        advancedSecurityMonitoring: 'Advanced security monitoring and threat detection',
        cloudStorage: 'Cloud Storage',
        secureCloudStorage: 'Secure cloud storage with automatic backup and sync',
        databasePro: 'Database Pro',
        professionalDatabaseManagement: 'Professional database management with advanced querying',
        
        // Additional Service Features
        realTimeAnalytics: 'Real-time analytics',
        basicReports: 'Basic reports',
        emailSupport: 'Email support',
        storage5GB: '5GB storage',
        advancedAIAnalytics: 'Advanced AI analytics',
        machineLearning: 'Machine learning',
        prioritySupport: 'Priority support',
        storage50GB: '50GB storage',
        customReports: 'Custom reports',
        unlimitedAnalytics: 'Unlimited analytics',
        fullAISuite: 'Full AI suite',
        dedicatedSupport: '24/7 dedicated support',
        unlimitedStorage: 'Unlimited storage',
        customIntegrations: 'Custom integrations',
        apiAccess: 'API access',
        securityMonitoring: 'Security monitoring',
        threatDetection: 'Threat detection',
        complianceReporting: 'Compliance reporting',
        securityAlerts: 'Security alerts',
        storage100GB: '100GB storage',
        automaticBackup: 'Automatic backup',
        fileSync: 'File sync',
        secureSharing: 'Secure sharing',
        databaseManagement: 'Database management',
        advancedQueries: 'Advanced queries',
        performanceOptimization: 'Performance optimization',
        dataBackup: 'Data backup',
        
        // Payment Methods
        mobilePayment: 'Mobile Payment',
        payUsingMobile: 'Pay using mobile wallet or banking app',
        bankTransfer: 'Bank Transfer',
        directBankTransfer: 'Direct bank transfer to our account',
        
        // Dashboard Stats
        neuralAnalyticsPro: 'Neural Analytics Pro',
        quantumComputing: 'Quantum Computing',
        realTimeProcessing: 'Real-time Processing',
        dedicatedResources: 'Dedicated Resources',
        quantumAlgorithms: 'Quantum Algorithms',
        highPerformance: 'High Performance',
        
        // Achievements
        powerUser: 'Power User',
        over1MApiCalls: 'Over 1M API calls',
        innovationLeader: 'Innovation Leader',
        usingAdvancedFeatures: 'Using advanced features',
        pleaseEnterValidAmount: 'Please enter a valid amount',
        pleaseUploadPaymentScreenshot: 'Please upload payment screenshot',
        paymentVerificationSubmitted: 'Payment verification submitted successfully! Your wallet will be updated within 24 hours.',
        failedToSubmitPayment: 'Failed to submit payment verification',
        addFundsToWallet: 'Add funds to your wallet securely and quickly',
        chooseFile: 'Choose file',
        orDragAndDrop: 'or drag and drop',
        fileUploadInfo: 'PNG, JPG, GIF up to 10MB',
        close: 'Close',
        enterPhoneNumber: 'Enter your phone number',
        referralCodeDetected: 'Referral code detected! You can proceed with login or signup.',
        loginSuccessful: 'Login successful! Redirecting to dashboard...',
        loginFailed: 'Login failed. Please check your credentials and try again.',
        passwordsDoNotMatch: 'Passwords do not match',
        passwordMustBe6Chars: 'Password must be at least 6 characters long',
        accountCreatedSuccess: 'Account created successfully! Please check your email to verify your account.',
        signupFailed: 'Signup failed. Please try again later.',
        availableForServices: 'Available for services',
        analytics: 'Analytics',
        neuralIntelligence: 'Neural Intelligence',
        neuralIntelligenceDesc: 'Advanced neural networks that learn and adapt to your unique business patterns with unprecedented accuracy.',
        quantumProcessing: 'Quantum Processing',
        quantumProcessingDesc: 'Harness the power of quantum-inspired algorithms for lightning-fast data processing and insights.',
        militaryGradeSecurity: 'Military-Grade Security',
        militaryGradeSecurityDesc: 'Enterprise-level encryption with biometric authentication and real-time threat detection.',
        hypersonicPerformance: 'Hypersonic Performance',
        hypersonicPerformanceDesc: 'Sub-millisecond response times with our proprietary optimization technology.',
        predictiveAnalytics: 'Predictive Analytics',
        predictiveAnalyticsDesc: 'Forecast trends and opportunities with 99.9% accuracy using our advanced ML models.',
        premiumSupport: 'Premium Support',
        premiumSupportDesc: '24/7 dedicated support with AI-powered assistance and human experts.',
        aiPlatform: 'AI Platform'
      },
      ar: {
        // Navigation
        home: 'الرئيسية',
        dashboard: 'لوحة التحكم',
        services: 'الخدمات',
        wallet: 'المحفظة',
        reports: 'التقارير',
        login: 'تسجيل الدخول',
        signup: 'إنشاء حساب',
        logout: 'تسجيل الخروج',
        
        // Common
        loading: 'جاري التحميل...',
        error: 'خطأ',
        success: 'نجاح',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        view: 'عرض',
        
        // User Dashboard
        balance: 'الرصيد',
        subscriptions: 'الاشتراكات النشطة',
        noSubscriptions: 'لا توجد اشتراكات نشطة',
        subscribeNow: 'اشترك الآن',
        premiumNotification: 'لضمان خدمة أفضل اشترك في الخطة المميزة',
        welcomeBack: 'مرحباً بعودتك!',
        dashboardSubtitle: 'لوحة التحكم المدعومة بالذكاء الاصطناعي تعمل بأداء مثالي',
        accountBalance: 'رصيد الحساب',
        activeServices: 'الخدمات النشطة',
        enterpriseEliteUpgrade: 'ترقية النخبة للمؤسسات متاحة',
        unlockQuantumProcessing: 'فتح المعالجة الكمية غير المحدودة والبنية التحتية للذكاء الاصطناعي المخصصة',
        upgradeNow: 'رقّي الآن',
        accountStatus: 'حالة الحساب',
        premium: 'مميز',
        performance: 'الأداء',
        uptime: 'وقت التشغيل هذا الشهر',
        optimal: 'مثالي',
        activeSubscriptions: 'الاشتراكات النشطة',
        browseServices: 'تصفح الخدمات',
        noActiveSubscriptions: 'لا توجد اشتراكات نشطة',
        subscribeToPremium: 'اشترك في خدماتنا المميزة لفتح الميزات المتقدمة',
        exploreServices: 'استكشف الخدمات',
        nextBilling: 'الفوترة التالية',
        yourAchievements: 'إنجازاتك',
        manageYourFunds: 'إدارة أموالك',
        viewWallet: 'عرض المحفظة',
        browsePremiumServices: 'تصفح الخدمات المميزة',
        viewServices: 'عرض الخدمات',
        advancedInsights: 'رؤى متقدمة',
        comingSoon: 'قريباً',
        accountPreferences: 'تفضيلات الحساب',
        settings: 'الإعدادات',
        
        // Services
        price: 'السعر',
        subscribe: 'اشترك',
        subscribed: 'مشترك',
        insufficientBalance: 'رصيد غير كافٍ',
        premiumServices: 'خدمات مميزة',
        currentBalance: 'الرصيد الحالي',
        choosePerfectPlan: 'اختر الخطة المثالية لاحتياجاتك وافتح ميزات قوية',
        mostPopular: 'الأكثر شعبية',
        confirmSubscription: 'تأكيد الاشتراك',
        currentBalanceLabel: 'الرصيد الحالي:',
        subscriptionCost: 'تكلفة الاشتراك:',
        balanceAfterSubscription: 'الرصيد بعد الاشتراك:',
        areYouSureSubscribe: 'هل أنت متأكد من أنك تريد الاشتراك في هذه الخدمة؟',
        
        // Wallet
        walletRecharge: 'شحن المحفظة',
        phoneNumber: 'رقم الهاتف',
        amount: 'المبلغ',
        uploadScreenshot: 'رفع لقطة الشاشة الدفع',
        submit: 'إرسال',
        rechargeForm: 'نموذج الشحن',
        paymentMethod: 'طريقة الدفع',
        paymentDetails: 'تفاصيل الدفع',
        sendPaymentTo: 'أرسل الدفع إلى:',
        includeUserIdInReference: 'يرجى تضمين معرف المستخدم في مرجع الدفع',
        howToRecharge: 'كيفية الشحن',
        selectPaymentMethod: 'اختر طريقة الدفع المفضلة لديك',
        enterAmount: 'أدخل المبلغ الذي تريد إضافته',
        sendPayment: 'أرسل الدفع إلى الرقم/الحساب المقدم',
        uploadPaymentProof: 'ارفع لقطة شاشة الدفع كإثبات',
        submitForVerification: 'قدم للتحقق',
        notePaymentVerification: 'ملاحظة: عملية التحقق من الدفع تستغرق عادةً من 1 إلى 24 ساعة. ستتلقى إشعارًا بمجرد تحديث محفظتك.',
        paymentScreenshotPreview: 'معاينة لقطة شاشة الدفع',
        
        // Marketing Dashboard
        totalReferred: 'إجمالي المستخدمين المُحالين',
        availableEarnings: 'الأرباح المتاحة',
        referralLink: 'رابط الإحالة',
        paidReferrals: 'الإحالات المدفوعة',
        
        // Admin Dashboard
        totalUsers: 'إجمالي المستخدمين',
        payingUsers: 'المستخدمون الدافعون',
        marketingUsers: 'مستخدمو التسويق',
        totalPaid: 'إجمالي المبلغ المدفوع',
        marketingBudget: 'ميزانية التسويق',
        
        // Auth
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        confirmPassword: 'تأكيد كلمة المرور',
        rememberMe: 'تذكرني',
        forgotPassword: 'نسيت كلمة المرور؟',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        dontHaveAccount: 'ليس لديك حساب؟',
        premiumAccess: 'وصول مميز',
        createAccount: 'أنشئ حسابك وابدأ اليوم!',
        fullName: 'الاسم الكامل',
        enterFullName: 'أدخل اسمك الكامل',
        enterEmail: 'أدخل بريدك الإلكتروني',
        createPassword: 'أنشئ كلمة مرور',
        enterPassword: 'أدخل كلمة المرور',
        confirmPasswordLabel: 'أكد كلمة المرور',
        referralCodeOptional: 'رمز الإحالة (اختياري)',
        enterReferralCode: 'أدخل رمز الإحالة',
        
        // Landing
        welcome: 'مرحباً بك في منصة الذكاء الاصطناعي',
        subtitle: 'اختبر مستقبل الخدمات المدعومة بالذكاء الاصطناعي',
        getStarted: 'ابدأ الآن',
        features: 'المميزات',
        about: 'حول',
        contact: 'اتصل بنا',
        enterpriseGrade: 'درجة المؤسسة',
        nextGenerationAI: 'منصة الذكاء الاصطناعي من الجيل التالي',
        transformBusiness: 'حول أعمالك بتقنيات الذكاء الاصطناعي المتطورة والحوسبة الكمومية',
        startFreeTrial: 'ابدأ التجربة المجانية',
        viewDemo: 'عرض تجريبي',
        revolutionaryFeatures: 'ميزات ثورية',
        experienceFutureAI: 'اختبر مستقبل الذكاء الاصطناعي مع مجموعة التقنيات المتطورة لدينا',
        limitedTimeOffer: 'عرض لفترة محدودة',
        readyToDominate: 'هل أنت مستعد للسيطرة على صناعتك؟',
        joinEliteBusinesses: 'انضم إلى الشركات النخبة التي تستفيد بالفعل من منصتنا للذكاء الاصطناعي لتحقيق نمو وكفاءة غير مسبوقين.',
        startYourJourney: 'ابدأ رحلتك',
        scheduleDemo: 'جدول تجريبي',
        rating: 'تقييم 4.9/5',
        secure: 'آمن بنسبة 100%',
        enterpriseReady: 'جاهز للمؤسسات',
        apiCalls: 'مكالمات API',
        responseTime: 'وقت الاستجابة',
        support: 'الدعم',
        
        // Additional Service Names
        basicAnalytics: 'التحليلات الأساسية',
        essentialAnalyticsBusiness: 'تحليلات أساسية لأعمالك مع رؤى في الوقت الفعلي',
        professionalAI: 'الذكاء الاصطناعي الاحترافي',
        advancedAIPowered: 'تحليلات متقدمة مدعومة بالذكاء الاصطناعي مع قدرات التعلم الآلي',
        enterpriseSuite: 'حزمة المؤسسات',
        completeEnterpriseSolution: 'حل كامل للمؤسسات بميزات غير محدودة ودعم',
        securityPro: 'الأمن الاحترافي',
        advancedSecurityMonitoring: 'مراقبة أمنية متقدمة وكشف عن التهديدات',
        cloudStorage: 'التخزين السحابي',
        secureCloudStorage: 'تخزين سحابي آمن مع النسخ الاحتياطي والمزامنة التلقائية',
        databasePro: 'قاعدة البيانات الاحترافية',
        professionalDatabaseManagement: 'إدارة قواعد بيانات احترافية مع استعلامات متقدمة',
        
        // Additional Service Features
        realTimeAnalytics: 'تحليلات في الوقت الفعلي',
        basicReports: 'تقارير أساسية',
        emailSupport: 'دعم البريد الإلكتروني',
        storage5GB: 'تخزين 5 جيجابايت',
        advancedAIAnalytics: 'تحليلات ذكاء اصطناعي متقدمة',
        machineLearning: 'التعلم الآلي',
        prioritySupport: 'دعم الأولوية',
        storage50GB: 'تخزين 50 جيجابايت',
        customReports: 'تقارير مخصصة',
        unlimitedAnalytics: 'تحليلات غير محدودة',
        fullAISuite: 'حزمة ذكاء اصطناعي كاملة',
        dedicatedSupport: 'دعم مخصص على مدار الساعة',
        unlimitedStorage: 'تخزين غير محدود',
        customIntegrations: 'تكاملات مخصصة',
        apiAccess: 'وصول API',
        securityMonitoring: 'مراقبة الأمن',
        threatDetection: 'كشف التهديدات',
        complianceReporting: 'تقارير الامتثال',
        securityAlerts: 'تنبيهات أمنية',
        storage100GB: 'تخزين 100 جيجابايت',
        automaticBackup: 'نسخ احتياطي تلقائي',
        fileSync: 'مزامنة الملفات',
        secureSharing: 'مشاركة آمنة',
        databaseManagement: 'إدارة قواعد البيانات',
        advancedQueries: 'استعلامات متقدمة',
        performanceOptimization: 'تحسين الأداء',
        dataBackup: 'نسخ احتياطي للبيانات',
        
        // Payment Methods
        mobilePayment: 'الدفع عبر المحمول',
        payUsingMobile: 'ادفع باستخدام المحفظة المحمولة أو تطبيق البنك',
        bankTransfer: 'التحويل البنكي',
        directBankTransfer: 'تحويل بنكي مباشر إلى حسابنا',
        
        // Dashboard Stats
        neuralAnalyticsPro: 'التحليلات العصبية الاحترافية',
        quantumComputing: 'الحوسبة الكمومية',
        realTimeProcessing: 'المعالجة في الوقت الفعلي',
        dedicatedResources: 'موارد مخصصة',
        quantumAlgorithms: 'خوارزميات كمومية',
        highPerformance: 'أداء عالي',
        
        // Achievements
        powerUser: 'مستخدم خبير',
        over1MApiCalls: 'أكثر من 1 مليون مكالمة API',
        innovationLeader: 'قائد الابتكار',
        usingAdvancedFeatures: 'باستخدام الميزات المتقدمة',
        pleaseEnterValidAmount: 'يرجى إدخال مبلغ صالح',
        pleaseUploadPaymentScreenshot: 'يرجى رفع لقطة شاشة الدفع',
        paymentVerificationSubmitted: 'تم إرسال التحقق من الدفع بنجاح! سيتم تحديث محفظتك خلال 24 ساعة.',
        failedToSubmitPayment: 'فشل في إرسال التحقق من الدفع',
        addFundsToWallet: 'أضف أموالاً إلى محفظتك بشكل آمن وسريع',
        chooseFile: 'اختر ملف',
        orDragAndDrop: 'أو اسحب وأفلت',
        fileUploadInfo: 'PNG, JPG, GIF حتى 10 ميجابايت',
        close: 'إغلاق',
        enterPhoneNumber: 'أدخل رقم هاتفك',
        referralCodeDetected: 'تم اكتشاف رمز الإحالة! يمكنك المتابعة بتسجيل الدخول أو إنشاء حساب.',
        loginSuccessful: 'تم تسجيل الدخول بنجاح! جاري إعادة التوجيه إلى لوحة التحكم...',
        loginFailed: 'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد والمحاولة مرة أخرى.',
        passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
        passwordMustBe6Chars: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
        accountCreatedSuccess: 'تم إنشاء الحساب بنجاح! يرجى التحقق من بريدك الإلكتروني لتفعيل حسابك.',
        signupFailed: 'فشل إنشاء الحساب. يرجى المحاولة مرة أخرى لاحقاً.',
        availableForServices: 'متاح للخدمات',
        analytics: 'التحليلات',
        neuralIntelligence: 'الذكاء العصبي',
        neuralIntelligenceDesc: 'شبكات عصبية متقدمة تتعلم وتتكيف مع أنماط عملك الفريدة بدقة غير مسبوقة.',
        quantumProcessing: 'المعالجة الكمومية',
        quantumProcessingDesc: 'استغل قوة الخوارزميات المستوحاة من الكم لمعالجة البيانات والرؤى بسرعة البرق.',
        militaryGradeSecurity: 'أمن عسكري',
        militaryGradeSecurityDesc: 'تشفير على مستوى المؤسسات مع المصادقة البيومترية وكشف التهديدات في الوقت الفعلي.',
        hypersonicPerformance: 'أداء فوق صوتي',
        hypersonicPerformanceDesc: 'أوقات استجابة أقل من مللي ثانية بتقنية التحسين الملكية لدينا.',
        predictiveAnalytics: 'التحليلات التنبؤية',
        predictiveAnalyticsDesc: 'توقع الاتجاهات والفرص بدقة 99.9٪ باستخدام نماذج التعلم الآلي المتقدمة لدينا.',
        premiumSupport: 'الدعم المميز',
        premiumSupportDesc: 'دعم مخصص على مدار الساعة بمساعدة مدعومة بالذكاء الاصطناعي وخبراء بشريين.',
        aiPlatform: 'منصة الذكاء الاصطناعي'
      }
    };
    
    const safeLanguage = language && translations[language] ? language : 'en';
    return translations[safeLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};