export const translations = {
  en: {
    // Common
    login: "Login",
    logout: "Logout",
    username: "Username",
    password: "Password",
    welcome: "Welcome",
    theme: "Theme",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    invalidCredentials: "Invalid username or password",
    allFieldsRequired: "All fields are required",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    pleaseSelectImage: "Please select an image file",
    fileTooLarge: "File size must be less than 5MB",
    enterFullName: "Please enter your full name",
    uploadScreenshot: "Please upload a payment screenshot",
    paymentSubmitted: "Payment submitted successfully",
    walletUpdated: "Wallet number updated successfully",

    // Landing Page - New Modern Design
    landingNewTagline: "The Future of Payments is Here",
    landingNewSubtitle:
      "Experience seamless, secure, and intelligent payment solutions designed for the modern business",
    landingNewGetStarted: "Start Free Trial",
    landingNewWatchDemo: "Watch Demo",
    landingNewHowItWorks: "How It Works",
    landingNewStep1: "Sign Up",
    landingNewStep1Desc: "Create your account in minutes",
    landingNewStep2: "Integrate",
    landingNewStep2Desc: "Connect with our easy-to-use API",
    landingNewStep3: "Start Processing",
    landingNewStep3Desc: "Accept payments immediately",
    landingNewTrustedBy: "Trusted by Industry Leaders",
    landingNewTestimonials: "What Our Clients Say",
    landingNewTestimonial1:
      "This platform transformed how we handle payments. The speed and security are unmatched.",
    landingNewTestimonial1Author: "Sarah Johnson, CEO of TechCorp",
    landingNewTestimonial2:
      "The analytics dashboard gives us insights we never had before. Game-changer for our business.",
    landingNewTestimonial2Author: "Michael Chen, CFO of InnovateCo",
    landingNewTestimonial3:
      "Customer support is exceptional. They helped us customize the solution perfectly.",
    landingNewTestimonial3Author:
      "Emma Rodriguez, Director of Finance at GlobalTech",
    landingNewReadyToStart: "Ready to Transform Your Business?",
    landingNewJoinRevolution: "Join the payment revolution today",
    landingNewFeaturesTitle: "Powerful Features",
    landingNewFeatureSecurity: "Bank-Grade Security",
    landingNewFeatureSecurityDesc:
      "Advanced encryption and fraud detection systems protect every transaction",
    landingNewFeatureSpeed: "Lightning-Fast Processing",
    landingNewFeatureSpeedDesc:
      "Process payments in milliseconds with our optimized infrastructure",
    landingNewFeatureAnalytics: "Smart Analytics",
    landingNewFeatureAnalyticsDesc:
      "Real-time insights and customizable reports to grow your business",
    landingNewFeatureGlobal: "Global Reach",
    landingNewFeatureGlobalDesc:
      "Accept payments in 135+ currencies from anywhere in the world",
    landingNewFeatureAPI: "Developer-Friendly API",
    landingNewFeatureAPIDesc:
      "Simple integration with comprehensive documentation and SDKs",
    landingNewFeatureSupport: "24/7 Expert Support",
    landingNewFeatureSupportDesc:
      "Our team is always ready to help you succeed",
    landingNewPricingTitle: "Simple, Transparent Pricing",
    landingNewPricingBasic: "Basic",
    landingNewPricingBasicPrice: "$29",
    landingNewPricingBasicDesc: "Perfect for small businesses getting started",
    landingNewPricingPro: "Professional",
    landingNewPricingProPrice: "$99",
    landingNewPricingProDesc: "For growing businesses with advanced needs",
    landingNewPricingEnterprise: "Enterprise",
    landingNewPricingEnterprisePrice: "Custom",
    landingNewPricingEnterpriseDesc:
      "Tailored solutions for large organizations",
    landingNewPricingFeature1: "Secure Payments",
    landingNewPricingFeature2: "Basic Analytics",
    landingNewPricingFeature3: "Email Support",
    landingNewPricingFeature4: "Advanced Analytics",
    landingNewPricingFeature5: "Priority Support",
    landingNewPricingFeature6: "API Access",
    landingNewPricingFeature7: "Custom Integration",
    landingNewPricingFeature8: "Dedicated Account Manager",
    landingNewPricingFeature9: "White-Label Solution",
    landingNewPricingGetStarted: "Get Started",
    landingNewPricingContactUs: "Contact Us",
    landingNewFAQTitle: "Frequently Asked Questions",
    landingNewFAQ1: "How long does setup take?",
    landingNewFAQ1Answer:
      "Most businesses are up and running in less than 15 minutes. Our intuitive setup process requires no technical expertise.",
    landingNewFAQ2: "What payment methods do you support?",
    landingNewFAQ2Answer:
      "We support all major credit cards, debit cards, digital wallets, and bank transfers in over 135 countries.",
    landingNewFAQ3: "Is my data secure?",
    landingNewFAQ3Answer:
      "Absolutely. We use bank-level encryption and comply with PCI DSS standards to ensure your data is always protected.",
    landingNewFAQ4: "Can I customize the payment experience?",
    landingNewFAQ4Answer:
      "Yes! Our platform is fully customizable to match your brand and provide a seamless customer experience.",
    landingNewCTATitle: "Ready to Get Started?",
    landingNewCTADesc:
      "Join thousands of businesses already growing with our payment platform",
    landingNewCTAButton: "Start Your Free Trial",

    // Login Page
    loginWelcomeBack: "Welcome Back",
    loginSignInToAccount: "Sign in to your account",
    loginReferralId: "Referral ID (Optional)",
    loginDemoUsers: "Demo Users",
    loginNormalUser: "Normal User",
    loginMarketingUser: "Marketing User",
    loginAdmin: "Admin",

    // Signup Page
    signupCreateAccount: "Create Account",
    signupJoinPlatform: "Join our premium payment platform",
    signupFullName: "Full Name",
    signupEmailAddress: "Email Address",
    signupCreatePassword: "Password",
    signupConfirmPassword: "Confirm Password",
    signupAccountType: "Account Type",
    signupNormalUser: "Normal User",
    signupMarketingUser: "Marketing User",
    signupReferralId: "Referral ID (Optional)",
    signupEnterReferralId: "Enter referral ID if you have one",
    signupCreateAccountBtn: "Create Account",
    signupHaveAccount: "Already have an account?",
    signupSignIn: "Sign In",

    // Dashboard
    dashboard: "Dashboard",
    services: "Services",
    selectService: "Select a Service",
    price: "Price",
    walletNumber: "Wallet Number",
    fullName: "Full Name",
    submitPayment: "Submit Payment",
    notifications: "Notifications",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    referralId: "Referral ID",
    referredUsers: "Referred Users",
    totalPayments: "Total Payments",
    adminPanel: "Admin Panel",
    users: "Users",
    stats: "Statistics",
    totalUsers: "Total Users",
    marketerStats: "Marketer Stats",
    manageServices: "Manage Services",
    serviceName: "Service Name",
    addService: "Add Service",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    paymentSubmissions: "Payment Submissions",
    approve: "Approve",
    reject: "Reject",
    noServices: "No services available",
    noNotifications: "No notifications",
    noUsers: "No users found",
    noPayments: "No payments found",
  },
  ar: {
    // Common
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    welcome: "مرحباً",
    theme: "المظهر",
    language: "اللغة",
    darkMode: "الوضع المظلم",
    lightMode: "الوضع الفاتح",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
    allFieldsRequired: "جميع الحقول مطلوبة",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    pleaseSelectImage: "الرجاء اختيار ملف صورة",
    fileTooLarge: "يجب أن يكون حجم الملف أقل من 5 ميجابايت",
    enterFullName: "الرجاء إدخال الاسم الكامل",
    uploadScreenshot: "الرجاء رفع لقطة شاشة الدفع",
    paymentSubmitted: "تم إرسال الدفع بنجاح",
    walletUpdated: "تم تحديث رقم المحفظة بنجاح",

    // Landing Page - New Modern Design
    landingNewTagline: "مستقبل الدفعات هنا",
    landingNewSubtitle: "اختبر حلول دفع سلسة وآمنة وذكية مصممة للأعمال الحديثة",
    landingNewGetStarted: "ابدأ التجربة المجانية",
    landingNewWatchDemo: "شاهد العرض التوضيحي",
    landingNewHowItWorks: "كيف يعمل",
    landingNewStep1: "سجل",
    landingNewStep1Desc: "أنشئ حسابك في دقائق",
    landingNewStep2: "دمج",
    landingNewStep2Desc: "اتصل بواجهة برمجة التطبيقات سهلة الاستخدام",
    landingNewStep3: "ابدأ المعالجة",
    landingNewStep3Desc: "اقبل الدفعات فوراً",
    landingNewTrustedBy: "موثوق به من قادة الصناعة",
    landingNewTestimonials: "ما يقوله عملاؤنا",
    landingNewTestimonial1:
      "هذه المنصة غيرت طريقة تعاملنا مع الدفعات. السرعة والأمان لا مثيل لهما.",
    landingNewTestimonial1Author: "سارة جونسون، الرئيس التنفيذي لشركة تككورب",
    landingNewTestimonial2:
      "لوحة التحليلات تمنحنا رؤى لم نكن نملكها من قبل. تغيير قواعد اللعبة لأعمالنا.",
    landingNewTestimonial2Author: "مايكل تشين، المدير المالي لشركة إنوفيتكو",
    landingNewTestimonial3:
      "دعم العملاء استثنائي. ساعدونا في تخصيص الحل بشكل مثالي.",
    landingNewTestimonial3Author:
      "إيما رودريغيز، مدير المالية في شركة جلوبالتك",
    landingNewReadyToStart: "هل أنت مستعد لتحويل عملك؟",
    landingNewJoinRevolution: "انضم إلى ثورة الدفع اليوم",
    landingNewFeaturesTitle: "ميزات قوية",
    landingNewFeatureSecurity: "أمان على مستوى البنوك",
    landingNewFeatureSecurityDesc:
      "أنظمة التشفير المتقدمة وكشف الاحتيال تحمي كل معاملة",
    landingNewFeatureSpeed: "معالجة سريعة كالبرق",
    landingNewFeatureSpeedDesc:
      "عالج المدفوعات في أجزاء من الثانية مع بنيتنا التحتية المُحسَّنة",
    landingNewFeatureAnalytics: "تحليلات ذكية",
    landingNewFeatureAnalyticsDesc:
      "رؤى في الوقت الفعلي وتقارير قابلة للتخصيص لنمو عملك",
    landingNewFeatureGlobal: "وصول عالمي",
    landingNewFeatureGlobalDesc:
      "اقبل الدفعات بـ 135+ عملة من أي مكان في العالم",
    landingNewFeatureAPI: "واجهة برمجة تطبيقات صديقة للمطورين",
    landingNewFeatureAPIDesc:
      "تكامل بسيط مع توثيق شامل ومجموعات تطوير البرمجيات",
    landingNewFeatureSupport: "دعم خبراء على مدار الساعة",
    landingNewFeatureSupportDesc: "فريقنا دائماً جاهز لمساعدتك على النجاح",
    landingNewPricingTitle: "أسعار بسيطة وشفافة",
    landingNewPricingBasic: "أساسي",
    landingNewPricingBasicPrice: "$29",
    landingNewPricingBasicDesc: "مثالي للشركات الصغيرة البادئة",
    landingNewPricingPro: "احترافي",
    landingNewPricingProPrice: "$99",
    landingNewPricingProDesc: "للشركات النامية ذات الاحتياجات المتقدمة",
    landingNewPricingEnterprise: "مؤسسي",
    landingNewPricingEnterprisePrice: "مخصص",
    landingNewPricingEnterpriseDesc: "حلول مخصصة للمؤسسات الكبيرة",
    landingNewPricingFeature1: "مدفوعات آمنة",
    landingNewPricingFeature2: "تحليلات أساسية",
    landingNewPricingFeature3: "دعم البريد الإلكتروني",
    landingNewPricingFeature4: "تحليلات متقدمة",
    landingNewPricingFeature5: "دعم الأولوية",
    landingNewPricingFeature6: "وصول API",
    landingNewPricingFeature7: "تكامل مخصص",
    landingNewPricingFeature8: "مدير حساب مخصص",
    landingNewPricingFeature9: "حل ذو علامة تجارية بيضاء",
    landingNewPricingGetStarted: "ابدأ",
    landingNewPricingContactUs: "اتصل بنا",
    landingNewFAQTitle: "الأسئلة الشائعة",
    landingNewFAQ1: "كم من الوقت يستغرق الإعداد؟",
    landingNewFAQ1Answer:
      "معظم الشركات تعمل وتعمل في أقل من 15 دقيقة. عملية الإعداد البديهية لدينا لا تتطلب خبرة فنية.",
    landingNewFAQ2: "ما هي طرق الدفع التي تدعمونها؟",
    landingNewFAQ2Answer:
      "ندعم جميع بطاقات الائتمان الرئيسية وبطاقات الخصم والمحافظ الرقمية والتحويلات المصرفية في أكثر من 135 دولة.",
    landingNewFAQ3: "هل بياناتي آمنة؟",
    landingNewFAQ3Answer:
      "بالتأكيد. نستخدم تشفيراً على مستوى البنوك ونتوافق مع معايير PCI DSS لضمان حماية بياناتك دائماً.",
    landingNewFAQ4: "هل يمكنني تخصيص تجربة الدفع؟",
    landingNewFAQ4Answer:
      "نعم! منصتنا قابلة للتخصيص بالكامل لتتناسب مع علامتك التجارية وتوفر تجربة عملاء سلسة.",
    landingNewCTATitle: "هل أنت مستعد للبدء؟",
    landingNewCTADesc:
      "انضم إلى آلاف الشركات التي تنمو بالفعل مع منصة الدفع الخاصة بنا",
    landingNewCTAButton: "ابدأ تجربتك المجانية",

    // Login Page
    loginWelcomeBack: "مرحباً بعودتك",
    loginSignInToAccount: "سجل الدخول إلى حسابك",
    loginReferralId: "معرف الإحالة (اختياري)",
    loginDemoUsers: "المستخدمون التجريبيون",
    loginNormalUser: "مستخدم عادي",
    loginMarketingUser: "مستخدم تسويق",
    loginAdmin: "المسؤول",

    // Signup Page
    signupCreateAccount: "إنشاء حساب",
    signupJoinPlatform: "انضم إلى منصة الدفع المتميزة لدينا",
    signupFullName: "الاسم الكامل",
    signupEmailAddress: "عنوان البريد الإلكتروني",
    signupCreatePassword: "كلمة المرور",
    signupConfirmPassword: "تأكيد كلمة المرور",
    signupAccountType: "نوع الحساب",
    signupNormalUser: "مستخدم عادي",
    signupMarketingUser: "مستخدم تسويق",
    signupReferralId: "معرف الإحالة (اختياري)",
    signupEnterReferralId: "أدخل معرف الإحالة إذا كان لديك",
    signupCreateAccountBtn: "إنشاء حساب",
    signupHaveAccount: "لديك حساب بالفعل؟",
    signupSignIn: "تسجيل الدخول",

    // Dashboard
    dashboard: "لوحة التحكم",
    services: "الخدمات",
    selectService: "اختر خدمة",
    price: "السعر",
    walletNumber: "رقم المحفظة",
    fullName: "الاسم الكامل",
    submitPayment: "إرسال الدفع",
    notifications: "الإشعارات",
    pending: "قيد الانتظار",
    approved: "مقبول",
    rejected: "مرفوض",
    referralId: "معرف الإحالة",
    referredUsers: "المستخدمون المُحالون",
    totalPayments: "إجمالي الدفعات",
    adminPanel: "لوحة المسؤول",
    users: "المستخدمون",
    stats: "الإحصائيات",
    totalUsers: "إجمالي المستخدمين",
    marketerStats: "إحصائيات المسوق",
    manageServices: "إدارة الخدمات",
    serviceName: "اسم الخدمة",
    addService: "إضافة خدمة",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    paymentSubmissions: "طلبات الدفع",
    approve: "موافقة",
    reject: "رفض",
    noServices: "لا توجد خدمات متاحة",
    noNotifications: "لا توجد إشعارات",
    noUsers: "لم يتم العثور على مستخدمين",
    noPayments: "لم يتم العثور على مدفوعات",
  },
};
