export const translations = {
  en: {
    // Common
    login: "Login",
    logout: "Logout",
    username: "Username",
    password: "Password",
    welcome: "Welcome",
    theme: "Theme",
    language: "Language",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    invalidCredentials: "Invalid username or password",
    allFieldsRequired: "All fields are required",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    pleaseSelectImage: "Please select an image file",
    fileTooLarge: "File size must be less than 5MB",
    enterFullName: "Please enter your full name",
    uploadScreenshot: "Please upload a payment screenshot",
    paymentSubmitted: "Payment submitted successfully",
    walletUpdated: "Wallet number updated successfully",
    referralId: "Referral ID",

    // Landing Page - New Modern Design
    landingNewTagline: "The Future of Payments is Here",
    landingNewSubtitle:
      "Experience seamless, secure, and intelligent payment solutions designed for the modern business",
    landingNewGetStarted: "Start Free Trial",
    landingNewWatchDemo: "Watch Demo",
    landingNewHowItWorks: "How It Works",
    landingNewStep1: "Sign Up",
    landingNewStep1Desc: "Create your account in minutes",
    landingNewStep2: "Integrate",
    landingNewStep2Desc: "Connect with our easy-to-use API",
    landingNewStep3: "Start Processing",
    landingNewStep3Desc: "Accept payments immediately",
    landingNewTrustedBy: "Trusted by Industry Leaders",
    landingNewTestimonials: "What Our Clients Say",
    landingNewTestimonial1:
      "This platform transformed how we handle payments. The speed and security are unmatched.",
    landingNewTestimonial1Author: "Sarah Johnson, CEO of TechCorp",
    landingNewTestimonial2:
      "The analytics dashboard gives us insights we never had before. Game-changer for our business.",
    landingNewTestimonial2Author: "Michael Chen, CFO of InnovateCo",
    landingNewTestimonial3:
      "Customer support is exceptional. They helped us customize the solution perfectly.",
    landingNewTestimonial3Author:
      "Emma Rodriguez, Director of Finance at GlobalTech",
    landingNewReadyToStart: "Ready to Transform Your Business?",
    landingNewJoinRevolution: "Join the payment revolution today",
    landingNewFeaturesTitle: "Powerful Features",
    landingNewFeatureSecurity: "Bank-Grade Security",
    landingNewFeatureSecurityDesc:
      "Advanced encryption and fraud detection systems protect every transaction",
    landingNewFeatureSpeed: "Lightning-Fast Processing",
    landingNewFeatureSpeedDesc:
      "Process payments in milliseconds with our optimized infrastructure",
    landingNewFeatureAnalytics: "Smart Analytics",
    landingNewFeatureAnalyticsDesc:
      "Real-time insights and customizable reports to grow your business",
    landingNewFeatureGlobal: "Global Reach",
    landingNewFeatureGlobalDesc:
      "Accept payments in 135+ currencies from anywhere in the world",
    landingNewFeatureAPI: "Developer-Friendly API",
    landingNewFeatureAPIDesc:
      "Simple integration with comprehensive documentation and SDKs",
    landingNewFeatureSupport: "24/7 Expert Support",
    landingNewFeatureSupportDesc:
      "Our team is always ready to help you succeed",
    landingNewPricingTitle: "Simple, Transparent Pricing",
    landingNewPricingBasic: "Basic",
    landingNewPricingBasicPrice: "$29",
    landingNewPricingBasicDesc: "Perfect for small businesses getting started",
    landingNewPricingPro: "Professional",
    landingNewPricingProPrice: "$99",
    landingNewPricingProDesc: "For growing businesses with advanced needs",
    landingNewPricingEnterprise: "Enterprise",
    landingNewPricingEnterprisePrice: "Custom",
    landingNewPricingEnterpriseDesc:
      "Tailored solutions for large organizations",
    landingNewPricingFeature1: "Secure Payments",
    landingNewPricingFeature2: "Basic Analytics",
    landingNewPricingFeature3: "Email Support",
    landingNewPricingFeature4: "Advanced Analytics",
    landingNewPricingFeature5: "Priority Support",
    landingNewPricingFeature6: "API Access",
    landingNewPricingFeature7: "Custom Integration",
    landingNewPricingFeature8: "Dedicated Account Manager",
    landingNewPricingFeature9: "White-Label Solution",
    landingNewPricingGetStarted: "Get Started",
    landingNewPricingContactUs: "Contact Us",
    landingNewFAQTitle: "Frequently Asked Questions",
    landingNewFAQ1: "How long does setup take?",
    landingNewFAQ1Answer:
      "Most businesses are up and running in less than 15 minutes. Our intuitive setup process requires no technical expertise.",
    landingNewFAQ2: "What payment methods do you support?",
    landingNewFAQ2Answer:
      "We support all major credit cards, debit cards, digital wallets, and bank transfers in over 135 countries.",
    landingNewFAQ3: "Is my data secure?",
    landingNewFAQ3Answer:
      "Absolutely. We use bank-level encryption and comply with PCI DSS standards to ensure your data is always protected.",
    landingNewFAQ4: "Can I customize the payment experience?",
    landingNewFAQ4Answer:
      "Yes! Our platform is fully customizable to match your brand and provide a seamless customer experience.",
    landingNewCTATitle: "Ready to Get Started?",
    landingNewCTADesc:
      "Join thousands of businesses already growing with our payment platform",
    landingNewCTAButton: "Start Your Free Trial",
    landingProduct: "Product",
    landingFeatures: "Features",
    landingPricing: "Pricing",
    landingIntegrations: "Integrations",
    landingApi: "API",
    landingCompany: "Company",
    landingAbout: "About",
    landingBlog: "Blog",
    landingCareers: "Careers",
    landingContact: "Contact",
    landingResources: "Resources",
    landingDocumentation: "Documentation",
    landingSupport: "Support",
    landingStatus: "Status",
    landingPartners: "Partners",
    landingLegal: "Legal",
    landingPrivacy: "Privacy",
    landingTerms: "Terms",
    landingSecurity: "Security",
    landingCompliance: "Compliance",
    landingAllRightsReserved: "All rights reserved.",

    // Login Page
    loginPageTitle: "Welcome Back",
    loginPageSubtitle: "Sign in to your account",
    loginUsernamePlaceholder: "Enter your username",
    loginPasswordPlaceholder: "Enter your password",
    loginReferralPlaceholder: "Enter referral ID (optional)",
    loginButton: "Sign In",
    loginNoAccount: "Don't have an account?",
    loginSignupLink: "Sign Up",
    loginDemoTitle: "Demo Users",
    loginDemoNormal: "Normal User: John Doe / password",
    loginDemoMarketing: "Marketing User: Jane Smith / password",
    loginDemoAdmin: "Admin: Admin User / password",

    // Signup Page
    signupPageTitle: "Create Account",
    signupPageSubtitle: "Join our premium payment platform",
    signupFullNamePlaceholder: "Enter your full name",
    signupEmailAddressPlaceholder: "Enter your email address",
    signupPasswordPlaceholder: "Create a password",
    signupConfirmPasswordPlaceholder: "Confirm your password",
    signupAccountTypeLabel: "Account Type",
    signupNormalUser: "Normal User",
    signupMarketingUser: "Marketing User",
    signupReferralPlaceholder: "Enter referral ID (optional)",
    signupButton: "Create Account",
    signupHaveAccount: "Already have an account?",
    signupLoginLink: "Sign In",

    // Dashboard
    dashboard: "Dashboard",
    services: "Services",
    selectService: "Select a Service",
    price: "Price",
    walletNumber: "Wallet Number",
    fullName: "Full Name",
    submitPayment: "Submit Payment",
    notifications: "Notifications",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    referredUsers: "Referred Users",
    totalPayments: "Total Payments",
    adminPanel: "Admin Panel",
    users: "Users",
    stats: "Statistics",
    totalUsers: "Total Users",
    marketerStats: "Marketer Stats",
    manageServices: "Manage Services",
    serviceName: "Service Name",
    addService: "Add Service",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    paymentSubmissions: "Payment Submissions",
    approve: "Approve",
    reject: "Reject",
    noServices: "No services available",
    noNotifications: "No notifications",
    noUsers: "No users found",
    noPayments: "No payments found",
    // Add these to the English section
    dashboardWelcome: "Welcome to your dashboard",
    dashboardSubtitle: "Manage your services and payments",
    dashboardServices: "Available Services",
    dashboardSelectService: "Select a service to make a payment",
    dashboardPaymentInfo: "Payment Information",
    dashboardWalletInfo: "Wallet Information",
    dashboardNotifications: "Recent Notifications",
    dashboardNoServices: "No services available at the moment",
    dashboardNoNotifications: "No notifications yet",
    dashboardPaymentSuccess: "Payment submitted successfully",
    dashboardPaymentError: "Error submitting payment",
    dashboardReferredUsersDesc:
      "Users who have joined using your referral code",
    dashboardPaymentsCount: "Payments",
    dashboardRevenue: "Revenue",
    dashboardPerformance: "Performance Metrics",
    dashboardPerformanceDesc: "Track your marketing performance and earnings",
    dashboardConversionRate: "Conversion Rate",
    dashboardAvgRevenue: "Avg. Revenue per User",
    dashboardTopService: "Top Service",
    dashboardNoReferredUsers:
      "No referred users yet. Start sharing your referral code!",
    dashboardAnalytics: "Analytics",
    dashboardMonthlyPerformance: "Monthly Performance",
    dashboardMonthlyPerformanceDesc:
      "Your referral performance over the last 6 months",
    dashboardTopServicesDesc: "Most popular services among your referrals",
    dashboardSales: "sales",
    dashboardStatus: "Status",
    dashboardActive: "Active",
    dashboardInactive: "Inactive",
    dashboardShareReferral: "Share Referral Code",
    dashboardGrowYourNetwork: "Grow Your Network",
    dashboardGrowYourNetworkDesc:
      "Share your referral code and earn more rewards",
    dashboardRecentActivity: "Recent Activity",
    dashboardRecentActivityDesc: "Latest updates from your referral network",
    dashboardNewUser: "New User Joined",
    dashboardNewUserDesc: "A new user joined using your referral code",
    dashboardPayment: "Payment Completed",
    dashboardPaymentDesc: "A payment was completed from your referral",
    dashboardMilestone: "Milestone Reached",
    dashboardMilestoneDesc: "You reached 50 referred users",
    dashboardConversionDesc: "Percentage of visitors who become customers",
    dashboardAvgRevenueDesc: "Average revenue generated per referred user",
    dashboardTopServiceDesc: "Most purchased service by your referrals",
    dashboardAvgTime: "Avg. Conversion Time",
    dashboardAvgTimeDesc:
      "Average time for a user to make their first purchase",
    dashboardPendingApprovals: "Pending Approvals",
    dashboardGrowthRate: "Growth Rate",
    dashboardNewUserReg: "New User Registration",
    dashboardNewUserRegDesc: "A new user registered on the platform",
    dashboardNewPayment: "New Payment Received",
    dashboardNewPaymentDesc:
      "A new payment was received and is pending approval",
    dashboardRevenueMilestone: "Revenue Milestone Reached",
    dashboardRevenueMilestoneDesc: "Total revenue has reached $10,000",
    dashboardUserGrowth: "User Growth",
    dashboardUserGrowthDesc: "Monthly user growth over the last 6 months",
    dashboardRevenueTrend: "Revenue Trend",
    dashboardRevenueTrendDesc: "Monthly revenue trend over the last 6 months",
    dashboardRoleDistribution: "User Role Distribution",
    dashboardPaymentStatus: "Payment Status Distribution",
    dashboardTopServices: "Top Services",
    dashboardAvgTransaction: "Average Transaction Value",
    dashboardAvgTransactionDesc: "Average value of all transactions",
    dashboardConversionRateDesc:
      "Percentage of visitors who become paying customers",
    dashboardAvgApprovalTime: "Average Approval Time",
    dashboardAvgApprovalTimeDesc: "Average time to approve a payment",
    dashboardManageUsers: "Manage all users in the system",
    dashboardSearchUsers: "Search users by name or referral ID",
    dashboardAllRoles: "All Roles",
    dashboardNormalUsers: "Normal Users",
    dashboardMarketingUsers: "Marketing Users",
    dashboardAdminUsers: "Admin Users",
    dashboardNoUsersFound: "No users found",
    dashboardActions: "Actions",
    dashboardDelete: "Delete",
    dashboardConfirmDelete: "Are you sure you want to delete this user?",
    dashboardManageServicesDesc: "Add, edit, or remove services",
    dashboardSearchServices: "Search services by name",
    dashboardNoServicesFound: "No services found",
    dashboardManagePayments: "Manage payment submissions",
    dashboardSearchPayments: "Search payments by user name",
    dashboardAllStatuses: "All Statuses",
    dashboardNoPaymentsFound: "No payments found",
    dashboardDate: "Date",
  },
  ar: {
    // Common
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    welcome: "مرحباً",
    theme: "المظهر",
    language: "اللغة",
    darkMode: "الوضع المظلم",
    lightMode: "الوضع الفاتح",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
    allFieldsRequired: "جميع الحقول مطلوبة",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    pleaseSelectImage: "الرجاء اختيار ملف صورة",
    fileTooLarge: "يجب أن يكون حجم الملف أقل من 5 ميجابايت",
    enterFullName: "الرجاء إدخال الاسم الكامل",
    uploadScreenshot: "الرجاء رفع لقطة شاشة الدفع",
    paymentSubmitted: "تم إرسال الدفع بنجاح",
    walletUpdated: "تم تحديث رقم المحفظة بنجاح",
    referralId: "معرف الإحالة",

    // Landing Page - New Modern Design
    landingNewTagline: "مستقبل الدفعات هنا",
    landingNewSubtitle: "اختبر حلول دفع سلسة وآمنة وذكية مصممة للأعمال الحديثة",
    landingNewGetStarted: "ابدأ التجربة المجانية",
    landingNewWatchDemo: "شاهد العرض التوضيحي",
    landingNewHowItWorks: "كيف يعمل",
    landingNewStep1: "سجل",
    landingNewStep1Desc: "أنشئ حسابك في دقائق",
    landingNewStep2: "دمج",
    landingNewStep2Desc: "اتصل بواجهة برمجة التطبيقات سهلة الاستخدام",
    landingNewStep3: "ابدأ المعالجة",
    landingNewStep3Desc: "اقبل الدفعات فوراً",
    landingNewTrustedBy: "موثوق به من قادة الصناعة",
    landingNewTestimonials: "ما يقوله عملاؤنا",
    landingNewTestimonial1:
      "هذه المنصة غيرت طريقة تعاملنا مع الدفعات. السرعة والأمان لا مثيل لهما.",
    landingNewTestimonial1Author: "سارة جونسون، الرئيس التنفيذي لشركة تككورب",
    landingNewTestimonial2:
      "لوحة التحليلات تمنحنا رؤى لم نكن نملكها من قبل. تغيير قواعد اللعبة لأعمالنا.",
    landingNewTestimonial2Author: "مايكل تشين، المدير المالي لشركة إنوفيتكو",
    landingNewTestimonial3:
      "دعم العملاء استثنائي. ساعدونا في تخصيص الحل بشكل مثالي.",
    landingNewTestimonial3Author:
      "إيما رودريغيز، مدير المالية في شركة جلوبالتك",
    landingNewReadyToStart: "هل أنت مستعد لتحويل عملك؟",
    landingNewJoinRevolution: "انضم إلى ثورة الدفع اليوم",
    landingNewFeaturesTitle: "ميزات قوية",
    landingNewFeatureSecurity: "أمان على مستوى البنوك",
    landingNewFeatureSecurityDesc:
      "أنظمة التشفير المتقدمة وكشف الاحتيال تحمي كل معاملة",
    landingNewFeatureSpeed: "معالجة سريعة كالبرق",
    landingNewFeatureSpeedDesc:
      "عالج المدفوعات في أجزاء من الثانية مع بنيتنا التحتية المُحسَّنة",
    landingNewFeatureAnalytics: "تحليلات ذكية",
    landingNewFeatureAnalyticsDesc:
      "رؤى في الوقت الفعلي وتقارير قابلة للتخصيص لنمو عملك",
    landingNewFeatureGlobal: "وصول عالمي",
    landingNewFeatureGlobalDesc:
      "اقبل الدفعات بـ 135+ عملة من أي مكان في العالم",
    landingNewFeatureAPI: "واجهة برمجة تطبيقات صديقة للمطورين",
    landingNewFeatureAPIDesc:
      "تكامل بسيط مع توثيق شامل ومجموعات تطوير البرمجيات",
    landingNewFeatureSupport: "دعم خبراء على مدار الساعة",
    landingNewFeatureSupportDesc: "فريقنا دائماً جاهز لمساعدتك على النجاح",
    landingNewPricingTitle: "أسعار بسيطة وشفافة",
    landingNewPricingBasic: "أساسي",
    landingNewPricingBasicPrice: "$29",
    landingNewPricingBasicDesc: "مثالي للشركات الصغيرة البادئة",
    landingNewPricingPro: "احترافي",
    landingNewPricingProPrice: "$99",
    landingNewPricingProDesc: "للشركات النامية ذات الاحتياجات المتقدمة",
    landingNewPricingEnterprise: "مؤسسي",
    landingNewPricingEnterprisePrice: "مخصص",
    landingNewPricingEnterpriseDesc: "حلول مخصصة للمؤسسات الكبيرة",
    landingNewPricingFeature1: "مدفوعات آمنة",
    landingNewPricingFeature2: "تحليلات أساسية",
    landingNewPricingFeature3: "دعم البريد الإلكتروني",
    landingNewPricingFeature4: "تحليلات متقدمة",
    landingNewPricingFeature5: "دعم الأولوية",
    landingNewPricingFeature6: "وصول API",
    landingNewPricingFeature7: "تكامل مخصص",
    landingNewPricingFeature8: "مدير حساب مخصص",
    landingNewPricingFeature9: "حل ذو علامة تجارية بيضاء",
    landingNewPricingGetStarted: "ابدأ",
    landingNewPricingContactUs: "اتصل بنا",
    landingNewFAQTitle: "الأسئلة الشائعة",
    landingNewFAQ1: "كم من الوقت يستغرق الإعداد؟",
    landingNewFAQ1Answer:
      "معظم الشركات تعمل وتعمل في أقل من 15 دقيقة. عملية الإعداد البديهية لدينا لا تتطلب خبرة فنية.",
    landingNewFAQ2: "ما هي طرق الدفع التي تدعمونها؟",
    landingNewFAQ2Answer:
      "ندعم جميع بطاقات الائتمان الرئيسية وبطاقات الخصم والمحافظ الرقمية والتحويلات المصرفية في أكثر من 135 دولة.",
    landingNewFAQ3: "هل بياناتي آمنة؟",
    landingNewFAQ3Answer:
      "بالتأكيد. نستخدم تشفيراً على مستوى البنوك ونتوافق مع معايير PCI DSS لضمان حماية بياناتك دائماً.",
    landingNewFAQ4: "هل يمكنني تخصيص تجربة الدفع؟",
    landingNewFAQ4Answer:
      "نعم! منصتنا قابلة للتخصيص بالكامل لتتناسب مع علامتك التجارية وتوفر تجربة عملاء سلسة.",
    landingNewCTATitle: "هل أنت مستعد للبدء؟",
    landingNewCTADesc:
      "انضم إلى آلاف الشركات التي تنمو بالفعل مع منصة الدفع الخاصة بنا",
    landingNewCTAButton: "ابدأ تجربتك المجانية",
    landingProduct: "المنتج",
    landingFeatures: "الميزات",
    landingPricing: "الأسعار",
    landingIntegrations: "التكاملات",
    landingApi: "واجهة برمجة التطبيقات",
    landingCompany: "الشركة",
    landingAbout: "من نحن",
    landingBlog: "المدونة",
    landingCareers: "الوظائف",
    landingContact: "اتصل بنا",
    landingResources: "الموارد",
    landingDocumentation: "التوثيق",
    landingSupport: "الدعم",
    landingStatus: "الحالة",
    landingPartners: "الشركاء",
    landingLegal: "قانوني",
    landingPrivacy: "الخصوصية",
    landingTerms: "الشروط",
    landingSecurity: "الأمان",
    landingCompliance: "الامتثال",
    landingAllRightsReserved: "جميع الحقوق محفوظة.",

    // Login Page
    loginPageTitle: "مرحباً بعودتك",
    loginPageSubtitle: "سجل الدخول إلى حسابك",
    loginUsernamePlaceholder: "أدخل اسم المستخدم",
    loginPasswordPlaceholder: "أدخل كلمة المرور",
    loginReferralPlaceholder: "أدخل معرف الإحالة (اختياري)",
    loginButton: "تسجيل الدخول",
    loginNoAccount: "ليس لديك حساب؟",
    loginSignupLink: "سجل",
    loginDemoTitle: "المستخدمون التجريبيون",
    loginDemoNormal: "مستخدم عادي: John Doe / password",
    loginDemoMarketing: "مستخدم تسويق: Jane Smith / password",
    loginDemoAdmin: "المسؤول: Admin User / password",

    // Signup Page
    signupPageTitle: "إنشاء حساب",
    signupPageSubtitle: "انضم إلى منصة الدفع المتميزة لدينا",
    signupFullNamePlaceholder: "أدخل اسمك الكامل",
    signupEmailAddressPlaceholder: "أدخل عنوان بريدك الإلكتروني",
    signupPasswordPlaceholder: "أنشئ كلمة مرور",
    signupConfirmPasswordPlaceholder: "أكّد كلمة المرور",
    signupAccountTypeLabel: "نوع الحساب",
    signupNormalUser: "مستخدم عادي",
    signupMarketingUser: "مستخدم تسويق",
    signupReferralPlaceholder: "أدخل معرف الإحالة (اختياري)",
    signupButton: "إنشاء حساب",
    signupHaveAccount: "لديك حساب بالفعل؟",
    signupLoginLink: "تسجيل الدخول",

    // Dashboard
    dashboard: "لوحة التحكم",
    services: "الخدمات",
    selectService: "اختر خدمة",
    price: "السعر",
    walletNumber: "رقم المحفظة",
    fullName: "الاسم الكامل",
    submitPayment: "إرسال الدفع",
    notifications: "الإشعارات",
    pending: "قيد الانتظار",
    approved: "مقبول",
    rejected: "مرفوض",
    referredUsers: "المستخدمون المُحالون",
    totalPayments: "إجمالي الدفعات",
    adminPanel: "لوحة المسؤول",
    users: "المستخدمون",
    stats: "الإحصائيات",
    totalUsers: "إجمالي المستخدمين",
    marketerStats: "إحصائيات المسوق",
    manageServices: "إدارة الخدمات",
    serviceName: "اسم الخدمة",
    addService: "إضافة خدمة",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    paymentSubmissions: "طلبات الدفع",
    approve: "موافقة",
    reject: "رفض",
    noServices: "لا توجد خدمات متاحة",
    noNotifications: "لا توجد إشعارات",
    noUsers: "لم يتم العثور على مستخدمين",
    noPayments: "لم يتم العثور على مدفوعات",
    dashboardWelcome: "مرحباً بك في لوحة التحكم",
    dashboardSubtitle: "إدارة خدماتك ودفعاتك",
    dashboardServices: "الخدمات المتاحة",
    dashboardSelectService: "اختر خدمة لإجراء دفع",
    dashboardPaymentInfo: "معلومات الدفع",
    dashboardWalletInfo: "معلومات المحفظة",
    dashboardNotifications: "الإشعارات الأخيرة",
    dashboardNoServices: "لا توجد خدمات متاحة في الوقت الحالي",
    dashboardNoNotifications: "لا توجد إشعارات بعد",
    dashboardPaymentSuccess: "تم إرسال الدفع بنجاح",
    dashboardPaymentError: "خطأ في إرسال الدفع",
    dashboardReferredUsersDesc:
      "المستخدمون الذين انضموا باستخدام رمز الإحالة الخاص بك",
    dashboardPaymentsCount: "المدفوعات",
    dashboardRevenue: "الإيرادات",
    dashboardPerformance: "مقاياس الأداء",
    dashboardPerformanceDesc: "تتبع أداء التسويق وأرباحك",
    dashboardConversionRate: "معدل التحويل",
    dashboardAvgRevenue: "متوسط الإيرادات لكل مستخدم",
    dashboardTopService: "الخدمة الأعلى",
    dashboardNoReferredUsers:
      "لا يوجد مستخدمون مُحالون بعد. ابدأ في مشاركة رمز الإحالة الخاص بك!",
    dashboardOverview: "نظرة عامة",
    dashboardAnalytics: "التحليلات",
    dashboardMonthlyPerformance: "الأداء الشهري",
    dashboardMonthlyPerformanceDesc:
      "أداء الإحالة الخاص بك خلال الـ 6 أشهر الماضية",
    dashboardTopServicesDesc: "الخدمات الأكثر شيوعًا بين إحالاتك",
    dashboardSales: "مبيعات",
    dashboardStatus: "الحالة",
    dashboardActive: "نشط",
    dashboardInactive: "غير نشط",
    dashboardShareReferral: "مشاركة رمز الإحالة",
    dashboardGrowYourNetwork: "قم بتوسيع شبكتك",
    dashboardGrowYourNetworkDesc:
      "شارك رمز الإحالة الخاص بك واكسب المزيد من المكافآت",
    dashboardRecentActivity: "النشاط الأخير",
    dashboardRecentActivityDesc: "أحدث التحديثات من شبكة الإحالة الخاصة بك",
    dashboardNewUser: "انضم مستخدم جديد",
    dashboardNewUserDesc: "انضم مستخدم جديد باستخدام رمز الإحالة الخاص بك",
    dashboardPayment: "اكتمل الدفع",
    dashboardPaymentDesc: "تم إتمام دفع من إحالتك",
    dashboardMilestone: "تم الوصول إلى معلم",
    dashboardMilestoneDesc: "وصلت إلى 50 مستخدم مُحال",
    dashboardConversionDesc: "نسبة الزوار الذين يصبحون عملاء",
    dashboardAvgRevenueDesc: "متوسط الإيرادات المولدة لكل مستخدم مُحال",
    dashboardTopServiceDesc: "الخدمة الأكثر شراءًا من قبل إحالاتك",
    dashboardAvgTime: "متوسط وقت التحويل",
    dashboardAvgTimeDesc:
      "متوسط الوقت الذي يستغرقه المستخدم لإجراء عملية الشراء الأولى",
    dashboardPendingApprovals: "الموافقات المعلقة",
    dashboardGrowthRate: "معدل النمو",
    dashboardNewUserReg: "تسجيل مستخدم جديد",
    dashboardNewUserRegDesc: "تم تسجيل مستخدم جديد على المنصة",
    dashboardNewPayment: "استلام دفعة جديدة",
    dashboardNewPaymentDesc: "تم استلام دفعة جديدة وهي في انتظار الموافقة",
    dashboardRevenueMilestone: "تحقيق معلم الإيرادات",
    dashboardRevenueMilestoneDesc: "وصلت الإيرادات الإجمالية إلى 10000 دولار",
    dashboardUserGrowth: "نمو المستخدمين",
    dashboardUserGrowthDesc: "نمو المستخدمين الشهري خلال الـ 6 أشهر الماضية",
    dashboardRevenueTrend: "اتجاه الإيرادات",
    dashboardRevenueTrendDesc: "اتجاه الإيرادات الشهري خلال الـ 6 أشهر الماضية",
    dashboardRoleDistribution: "توزيع أدوار المستخدمين",
    dashboardPaymentStatus: "توزيع حالة الدفع",
    dashboardTopServices: "الخدمات الأعلى",
    dashboardAvgTransaction: "متوسط قيمة المعاملة",
    dashboardAvgTransactionDesc: "متوسط قيمة جميع المعاملات",
    dashboardConversionRateDesc: "نسبة الزوار الذين يصبحون عملاء مدفوعين",
    dashboardAvgApprovalTime: "متوسط وقت الموافقة",
    dashboardAvgApprovalTimeDesc: "متوسط الوقت للموافقة على دفعة",
    dashboardManageUsers: "إدارة جميع المستخدمين في النظام",
    dashboardSearchUsers: "البحث عن المستخدمين بالاسم أو معرف الإحالة",
    dashboardAllRoles: "جميع الأدوار",
    dashboardNormalUsers: "المستخدمون العاديون",
    dashboardMarketingUsers: "مستخدمو التسويق",
    dashboardAdminUsers: "المسؤولون",
    dashboardNoUsersFound: "لم يتم العثور على مستخدمين",
    dashboardActions: "الإجراءات",
    dashboardDelete: "حذف",
    dashboardConfirmDelete: "هل أنت متأكد من أنك تريد حذف هذا المستخدم؟",
    dashboardManageServicesDesc: "إضافة أو تعديل أو إزالة الخدمات",
    dashboardSearchServices: "البحث عن الخدمات بالاسم",
    dashboardNoServicesFound: "لم يتم العثور على خدمات",
    dashboardManagePayments: "إدارة إرسالات الدفع",
    dashboardSearchPayments: "البحث عن المدفوعات باسم المستخدم",
    dashboardAllStatuses: "جميع الحالات",
    dashboardNoPaymentsFound: "لم يتم العثور على مدفوعات",
    dashboardDate: "التاريخ",
  },
};
